language: cpp
matrix:
  include:
    - os: linux
      dist: xenial
    - os: osx
      osx_image: xcode10.1
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install graphviz; fi
script:
  - cmake -G"Unix Makefiles" .
  - make
