version: 2
jobs:
  build:
    docker:
      - image: archlinux/base
    branches:
        only:
          - staging
    steps:
      - run:
          name: Install Dependencies
          command: |
           pacman -Syyu --noconfirm --noprogressbar --needed
           pacman -Sy base-devel git cmake --noconfirm --noprogressbar --needed
      - checkout
      - run:
          name: CI Build
          command: |
            cmake -G"Unix Makefiles" .
            make -j $(nproc)
            find -name libsquare.a
